apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-observability-lab
  namespace: service-lab
spec:
  replicas: 2
  selector:
    matchLabels: {app: service-observability-lab}
  template:
    metadata:
      labels: {app: service-observability-lab}
    spec:
      containers:
        - name: app
          image: ghcr.io/tefik-aliu/service-observability-lab:latest
          envFrom:
            - configMapRef: {name: service-lab-config}
            - secretRef: {name: service-lab-secrets}
          ports:
            - {containerPort: 8000}
          readinessProbe:
            httpGet: {path: /ready, port: 8000}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 512Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: service-observability-lab
  namespace: service-lab
spec:
  selector: {app: service-observability-lab}
  ports:
    - {port: 80, targetPort: 8000}
